//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FruitShopClient.FruitShopServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductType", Namespace="http://schemas.datacontract.org/2004/07/FruitShopServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class ProductType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FruitShopClient.FruitShopServiceReference.ProductDetails ProductDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FruitShopClient.FruitShopServiceReference.ProductDetails ProductDetails {
            get {
                return this.ProductDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductDetailsField, value) != true)) {
                    this.ProductDetailsField = value;
                    this.RaisePropertyChanged("ProductDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDetails", Namespace="http://schemas.datacontract.org/2004/07/FruitShopServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class ProductDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginDetails", Namespace="http://schemas.datacontract.org/2004/07/FruitShopServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class LoginDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/FruitShopServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OwnedProductType", Namespace="http://schemas.datacontract.org/2004/07/FruitShopServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class OwnedProductType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FruitShopClient.FruitShopServiceReference.ProductDetails ProductDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FruitShopClient.FruitShopServiceReference.ProductDetails ProductDetails {
            get {
                return this.ProductDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductDetailsField, value) != true)) {
                    this.ProductDetailsField = value;
                    this.RaisePropertyChanged("ProductDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FruitShopServiceReference.IFruitShopService")]
    public interface IFruitShopService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShopService/GetAvailableProducts", ReplyAction="http://tempuri.org/IFruitShopService/GetAvailableProductsResponse")]
        FruitShopClient.FruitShopServiceReference.ProductType[] GetAvailableProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShopService/GetAvailableProducts", ReplyAction="http://tempuri.org/IFruitShopService/GetAvailableProductsResponse")]
        System.Threading.Tasks.Task<FruitShopClient.FruitShopServiceReference.ProductType[]> GetAvailableProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShopService/RegisterCustomer", ReplyAction="http://tempuri.org/IFruitShopService/RegisterCustomerResponse")]
        FruitShopClient.FruitShopServiceReference.Message RegisterCustomer(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShopService/RegisterCustomer", ReplyAction="http://tempuri.org/IFruitShopService/RegisterCustomerResponse")]
        System.Threading.Tasks.Task<FruitShopClient.FruitShopServiceReference.Message> RegisterCustomerAsync(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShopService/LoginCustomer", ReplyAction="http://tempuri.org/IFruitShopService/LoginCustomerResponse")]
        bool LoginCustomer(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShopService/LoginCustomer", ReplyAction="http://tempuri.org/IFruitShopService/LoginCustomerResponse")]
        System.Threading.Tasks.Task<bool> LoginCustomerAsync(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShopService/AddProduct", ReplyAction="http://tempuri.org/IFruitShopService/AddProductResponse")]
        int AddProduct(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails, FruitShopClient.FruitShopServiceReference.ProductDetails productDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShopService/AddProduct", ReplyAction="http://tempuri.org/IFruitShopService/AddProductResponse")]
        System.Threading.Tasks.Task<int> AddProductAsync(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails, FruitShopClient.FruitShopServiceReference.ProductDetails productDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShopService/BuyProduct", ReplyAction="http://tempuri.org/IFruitShopService/BuyProductResponse")]
        FruitShopClient.FruitShopServiceReference.Message BuyProduct(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShopService/BuyProduct", ReplyAction="http://tempuri.org/IFruitShopService/BuyProductResponse")]
        System.Threading.Tasks.Task<FruitShopClient.FruitShopServiceReference.Message> BuyProductAsync(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShopService/GetBoughtProducts", ReplyAction="http://tempuri.org/IFruitShopService/GetBoughtProductsResponse")]
        FruitShopClient.FruitShopServiceReference.OwnedProductType[] GetBoughtProducts(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShopService/GetBoughtProducts", ReplyAction="http://tempuri.org/IFruitShopService/GetBoughtProductsResponse")]
        System.Threading.Tasks.Task<FruitShopClient.FruitShopServiceReference.OwnedProductType[]> GetBoughtProductsAsync(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShopService/GetBalance", ReplyAction="http://tempuri.org/IFruitShopService/GetBalanceResponse")]
        double GetBalance(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruitShopService/GetBalance", ReplyAction="http://tempuri.org/IFruitShopService/GetBalanceResponse")]
        System.Threading.Tasks.Task<double> GetBalanceAsync(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFruitShopServiceChannel : FruitShopClient.FruitShopServiceReference.IFruitShopService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FruitShopServiceClient : System.ServiceModel.ClientBase<FruitShopClient.FruitShopServiceReference.IFruitShopService>, FruitShopClient.FruitShopServiceReference.IFruitShopService {
        
        public FruitShopServiceClient() {
        }
        
        public FruitShopServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FruitShopServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FruitShopServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FruitShopServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FruitShopClient.FruitShopServiceReference.ProductType[] GetAvailableProducts() {
            return base.Channel.GetAvailableProducts();
        }
        
        public System.Threading.Tasks.Task<FruitShopClient.FruitShopServiceReference.ProductType[]> GetAvailableProductsAsync() {
            return base.Channel.GetAvailableProductsAsync();
        }
        
        public FruitShopClient.FruitShopServiceReference.Message RegisterCustomer(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails) {
            return base.Channel.RegisterCustomer(loginDetails);
        }
        
        public System.Threading.Tasks.Task<FruitShopClient.FruitShopServiceReference.Message> RegisterCustomerAsync(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails) {
            return base.Channel.RegisterCustomerAsync(loginDetails);
        }
        
        public bool LoginCustomer(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails) {
            return base.Channel.LoginCustomer(loginDetails);
        }
        
        public System.Threading.Tasks.Task<bool> LoginCustomerAsync(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails) {
            return base.Channel.LoginCustomerAsync(loginDetails);
        }
        
        public int AddProduct(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails, FruitShopClient.FruitShopServiceReference.ProductDetails productDetails) {
            return base.Channel.AddProduct(loginDetails, productDetails);
        }
        
        public System.Threading.Tasks.Task<int> AddProductAsync(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails, FruitShopClient.FruitShopServiceReference.ProductDetails productDetails) {
            return base.Channel.AddProductAsync(loginDetails, productDetails);
        }
        
        public FruitShopClient.FruitShopServiceReference.Message BuyProduct(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails, int productId) {
            return base.Channel.BuyProduct(loginDetails, productId);
        }
        
        public System.Threading.Tasks.Task<FruitShopClient.FruitShopServiceReference.Message> BuyProductAsync(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails, int productId) {
            return base.Channel.BuyProductAsync(loginDetails, productId);
        }
        
        public FruitShopClient.FruitShopServiceReference.OwnedProductType[] GetBoughtProducts(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails) {
            return base.Channel.GetBoughtProducts(loginDetails);
        }
        
        public System.Threading.Tasks.Task<FruitShopClient.FruitShopServiceReference.OwnedProductType[]> GetBoughtProductsAsync(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails) {
            return base.Channel.GetBoughtProductsAsync(loginDetails);
        }
        
        public double GetBalance(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails) {
            return base.Channel.GetBalance(loginDetails);
        }
        
        public System.Threading.Tasks.Task<double> GetBalanceAsync(FruitShopClient.FruitShopServiceReference.LoginDetails loginDetails) {
            return base.Channel.GetBalanceAsync(loginDetails);
        }
    }
}
